<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\CitySurfers.Application\CitySurfers.Application.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CitySurfers.UnitTests" />
    <InternalsVisibleTo Include="ProxyBuilder" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MongoDB.Driver" Version="3.12.0" />
  </ItemGroup>
</Project>
